name: ${project.name}
version: ${project.version}
description: ${project.description}
author: SmallCode
api-version: 1.13
main: it.smallcode.unbreakableItems.UnbreakableItems
commands:
  unbreakableitems: